language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="cmake ibglib2.0-dev libgranite-dev libgtk-3-dev libwingpanel-2.0-dev valac"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && cmake . && make"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && cmake . && make"

script:
- echo BUILDS PASSED
